export const ADMIN_GET_ALL_ACCOMODATIONS_REQUEST =
  'ADMIN_GET_ALL_ACCOMODATIONS_REQUEST';
export const ADMIN_GET_ALL_ACCOMODATIONS_SUCCESS =
  'ADMIN_GET_ALL_ACCOMODATIONS_SUCCESS';
export const ADMIN_GET_ALL_ACCOMODATIONS_FAIL =
  'ADMIN_GET_ALL_ACCOMODATIONS_FAIL';
export const ADMIN_GET_ALL_ACCOMODATIONS_RESET =
  'ADMIN_GET_ALL_ACCOMODATIONS_RESET';

export const ADMIN_GET_DETAILS_ACCOMODATIONS_REQUEST =
  'ADMIN_GET_DETAILS_ACCOMODATIONS_REQUEST';
export const ADMIN_GET_DETAILS_ACCOMODATIONS_SUCCESS =
  'ADMIN_GET_DETAILS_ACCOMODATIONS_SUCCESS';
export const ADMIN_GET_DETAILS_ACCOMODATIONS_FAIL =
  'ADMIN_GET_DETAILS_ACCOMODATIONS_FAIL';
export const ADMIN_GET_DETAILS_ACCOMODATIONS_RESET =
  'ADMIN_GET_DETAILS_ACCOMODATIONS_RESET';

export const ADMIN_CREATE_ACCOMODATIONS_REQUEST =
  'ADMIN_CREATE_ACCOMODATIONS_REQUEST';
export const ADMIN_CREATE_ACCOMODATIONS_SUCCESS =
  'ADMIN_CREATE_ACCOMODATIONS_SUCCESS';
export const ADMIN_CREATE_ACCOMODATIONS_FAIL =
  'ADMIN_CREATE_ACCOMODATIONS_FAIL';
export const ADMIN_CREATE_ACCOMODATIONS_RESET =
  'ADMIN_CREATE_ACCOMODATIONS_RESET';

export const ADMIN_DELETE_ACCOMODATIONS_REQUEST =
  'ADMIN_DELETE_ACCOMODATIONS_REQUEST';
export const ADMIN_DELETE_ACCOMODATIONS_SUCCESS =
  'ADMIN_DELETE_ACCOMODATIONS_SUCCESS';
export const ADMIN_DELETE_ACCOMODATIONS_FAIL =
  'ADMIN_DELETE_ACCOMODATIONS_FAIL';
export const ADMIN_DELETE_ACCOMODATIONS_RESET =
  'ADMIN_DELETE_ACCOMODATIONS_RESET';

export const ADMIN_EDIT_ACCOMODATIONS_REQUEST =
  'ADMIN_EDIT_ACCOMODATIONS_REQUEST';
export const ADMIN_EDIT_ACCOMODATIONS_SUCCESS =
  'ADMIN_EDIT_ACCOMODATIONS_SUCCESS';
export const ADMIN_EDIT_ACCOMODATIONS_FAIL = 'ADMIN_EDIT_ACCOMODATIONS_FAIL';
export const ADMIN_EDIT_ACCOMODATIONS_RESET = 'ADMIN_EDIT_ACCOMODATIONS_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
