export const GET_ALL_ADMIN_WELLNESS_BOOKING_REQUEST =
  'GET_ALL_ADMIN_WELLNESS_BOOKING_REQUEST';
export const GET_ALL_ADMIN_WELLNESS_BOOKING_SUCCESS =
  'GET_ALL_ADMIN_WELLNESS_BOOKING_SUCCESS';
export const GET_ALL_ADMIN_WELLNESS_BOOKING_FAIL =
  'GET_ALL_ADMIN_WELLNESS_BOOKING_FAIL';

export const GET_SINGLE_ADMIN_WELLNESS_BOOKING_REQUEST =
  'GET_SINGLE_ADMIN_WELLNESS_BOOKING_REQUEST';
export const GET_SINGLE_ADMIN_WELLNESS_BOOKING_SUCCESS =
  'GET_SINGLE_ADMIN_WELLNESS_BOOKING_SUCCESS';
export const GET_SINGLE_ADMIN_WELLNESS_BOOKING_FAIL =
  'GET_SINGLE_ADMIN_WELLNESS_BOOKING_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
