import {
  ADMIN_CREATE_ALL_WELLNESS_FAIL,
  ADMIN_CREATE_ALL_WELLNESS_RESET,
  ADMIN_CREATE_ALL_WELLNESS_REQUEST,
  ADMIN_CREATE_ALL_WELLNESS_SUCCESS,
  ADMIN_GET_ALL_WELLNESS_REQUEST,
  ADMIN_GET_ALL_WELLNESS_SUCCESS,
  ADMIN_GET_ALL_WELLNESS_FAIL,
  ADMIN_GET_DETAILS_WELLNESS_REQUEST,
  ADMIN_GET_DETAILS_WELLNESS_SUCCESS,
  ADMIN_GET_DETAILS_WELLNESS_FAIL,
} from '../../constants/admin/wellnessConstants';
