export const GET_ALL_ACCOMODATIONS_REQUEST = 'GET_ALL_ACCOMODATIONS_REQUEST';
export const GET_ALL_ACCOMODATIONS_SUCCESS = 'GET_ALL_ACCOMODATIONS_SUCCESS';
export const GET_ALL_ACCOMODATIONS_FAIL = 'GET_ALL_ACCOMODATIONS_FAIL';

export const GET_ACCOMODATION_DETAILS_REQUEST =
  'GET_ACCOMODATION_DETAILS_REQUEST';
export const GET_ACCOMODATION_DETAILS_SUCCESS =
  'GET_ACCOMODATION_DETAILS_SUCCESS';
export const GET_ACCOMODATION_DETAILS_FAIL = 'GET_ACCOMODATION_DETAILS_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
