export const BOOKING_DETAILS_ACCOMODATION_REQUEST =
  'BOOKING_DETAILS_ACCOMODATION_REQUEST';
export const BOOKING_DETAILS_ACCOMODATION_SUCCESS =
  'BOOKING_DETAILS_ACCOMODATION_SUCCESS';
export const BOOKING_DETAILS_ACCOMODATION_FAIL =
  'BOOKING_DETAILS_ACCOMODATION_FAIL';

export const BOOKING_ROOMID_ACCOMODATION_REQUEST =
  'BOOKING_ROOMID_ACCOMODATION_REQUEST';
export const BOOKING_ROOMID_ACCOMODATION_SUCCESS =
  'BOOKING_ROOMID_ACCOMODATION_SUCCESS';
export const BOOKING_ROOMID_ACCOMODATION_FAIL =
  'BOOKING_ROOMID_ACCOMODATION_FAIL';

export const BOOKING_USERDETAILS_ACCOMODATION_REQUEST =
  'BOOKING_USERDETAILS_ACCOMODATION_REQUEST';
export const BOOKING_USERDETAILS_ACCOMODATION_SUCCESS =
  'BOOKING_USERDETAILS_ACCOMODATION_SUCCESS';
export const BOOKING_USERDETAILS_ACCOMODATION_FAIL =
  'BOOKING_USERDETAILS_ACCOMODATION_FAIL';

export const RAZORPAY_BOOKING_ACCOMODATION_REQUEST =
  'RAZORPAY_BOOKING_ACCOMODATION_REQUEST';
export const RAZORPAY_BOOKING_ACCOMODATION_SUCCESS =
  'RAZORPAY_BOOKING_ACCOMODATION_SUCCESS';
export const RAZORPAY_BOOKING_ACCOMODATION_FAIL =
  'RAZORPAY_BOOKING_ACCOMODATION_FAIL';

export const GET_SINGLE_ACCOMODATION_BOOKING_REQUEST =
  'GET_SINGLE_ACCOMODATION_BOOKING_REQUEST';
export const GET_SINGLE_ACCOMODATION_BOOKING_SUCCESS =
  'GET_SINGLE_ACCOMODATION_BOOKING_SUCCESS';
export const GET_SINGLE_ACCOMODATION_BOOKING_FAIL =
  'GET_SINGLE_ACCOMODATION_BOOKING_FAIL';

export const GET_ALL_ADMIN_ACCOMODATION_BOOKING_REQUEST =
  'GET_ALL_ADMIN_ACCOMODATION_BOOKING_REQUEST';
export const GET_ALL_ADMIN_ACCOMODATION_BOOKING_SUCCESS =
  'GET_ALL_ADMIN_ACCOMODATION_BOOKING_SUCCESS';
export const GET_ALL_ADMIN_ACCOMODATION_BOOKING_FAIL =
  'GET_ALL_ADMIN_ACCOMODATION_BOOKING_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
