export const ADMIN_GET_ALL_ENQUIRIES_REQUEST =
  'ADMIN_GET_ALL_ENQUIRIES_REQUEST';
export const ADMIN_GET_ALL_ENQUIRIES_SUCCESS =
  'ADMIN_GET_ALL_ENQUIRIES_SUCCESS';
export const ADMIN_GET_ALL_ENQUIRIES_FAIL = 'ADMIN_GET_ALL_ENQUIRIES_FAIL';

export const USER_ENQUIRY_REQUEST = 'USER_ENQUIRY_REQUEST';
export const USER_ENQUIRY_SUCCESS = 'USER_ENQUIRY_SUCCESS';
export const USER_ENQUIRY_FAIL = 'USER_ENQUIRY_FAIL';
