export const ADMIN_GET_ALL_WELLNESS_ENQUIRIES_REQUEST =
  'ADMIN_GET_ALL_WELLNESS_ENQUIRIES_REQUEST';
export const ADMIN_GET_ALL_WELLNESS_ENQUIRIES_SUCCESS =
  'ADMIN_GET_ALL_WELLNESS_ENQUIRIES_SUCCESS';
export const ADMIN_GET_ALL_WELLNESS_ENQUIRIES_FAIL =
  'ADMIN_GET_ALL_WELLNESS_ENQUIRIES_FAIL';

export const USER_WELLNESS_ENQUIRY_REQUEST = 'USER_WELLNESS_ENQUIRY_REQUEST';
export const USER_WELLNESS_ENQUIRY_SUCCESS = 'USER_WELLNESS_ENQUIRY_SUCCESS';
export const USER_WELLNESS_ENQUIRY_FAIL = 'USER_WELLNESS_ENQUIRY_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
