export const BOOKING_DETAILS_WELLNESS_REQUEST =
  'BOOKING_DETAILS_WELLNESS_REQUEST';
export const BOOKING_DETAILS_WELLNESS_SUCCESS =
  'BOOKING_DETAILS_WELLNESS_SUCCESS';
export const BOOKING_DETAILS_WELLNESS_FAIL = 'BOOKING_DETAILS_WELLNESS_FAIL';

export const BOOKING_ROOMID_WELLNESS_REQUEST =
  'BOOKING_ROOMID_WELLNESS_REQUEST';
export const BOOKING_ROOMID_WELLNESS_SUCCESS =
  'BOOKING_ROOMID_WELLNESS_SUCCESS';
export const BOOKING_ROOMID_WELLNESS_FAIL = 'BOOKING_ROOMID_WELLNESS_FAIL';

export const BOOKING_USERDETAILS_WELLNESS_REQUEST =
  'BOOKING_USERDETAILS_WELLNESS_REQUEST';
export const BOOKING_USERDETAILS_WELLNESS_SUCCESS =
  'BOOKING_USERDETAILS_WELLNESS_SUCCESS';
export const BOOKING_USERDETAILS_WELLNESS_FAIL =
  'BOOKING_USERDETAILS_WELLNESS_FAIL';

export const RAZORPAY_BOOKING_WELLNESS_REQUEST =
  'RAZORPAY_BOOKING_WELLNESS_REQUEST';
export const RAZORPAY_BOOKING_WELLNESS_SUCCESS =
  'RAZORPAY_BOOKING_WELLNESS_SUCCESS';
export const RAZORPAY_BOOKING_WELLNESS_FAIL = 'RAZORPAY_BOOKING_WELLNESS_FAIL';

export const GET_SINGLE_WELLNESS_BOOKING_REQUEST =
  'GET_SINGLE_WELLNESS_BOOKING_REQUEST';
export const GET_SINGLE_WELLNESS_BOOKING_SUCCESS =
  'GET_SINGLE_WELLNESS_BOOKING_SUCCESS';
export const GET_SINGLE_WELLNESS_BOOKING_FAIL =
  'GET_SINGLE_WELLNESS_BOOKING_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
