export const GET_ALL_WELLNESS_REQUEST = 'GET_ALL_WELLNESS_REQUEST';
export const GET_ALL_WELLNESS_SUCCESS = 'GET_ALL_WELLNESS_SUCCESS';
export const GET_ALL_WELLNESS_FAIL = 'GET_ALL_WELLNESS_FAIL';
export const GET_ALL_WELLNESS_RESET = 'GET_ALL_WELLNESS_RESET';

export const GET_DETAILS_WELLNESS_REQUEST = 'GET_DETAILS_WELLNESS_REQUEST';
export const GET_DETAILS_WELLNESS_SUCCESS = 'GET_DETAILS_WELLNESS_SUCCESS';
export const GET_DETAILS_WELLNESS_FAIL = 'GET_DETAILS_WELLNESS_FAIL';
export const GET_DETAILS_WELLNESS_RESET = 'GET_ALL_WELLNESS_RESET';
